version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/config.py
  fail_on_warning: true
  
formats:
  - pdf
  
python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
