version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
  
formats:
  - pdf
  
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
