[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dartwrf"
authors = [{name = "Lukas Kugler", email = "lukas.kugler@univie.ac.at"}]
dynamic = ["version", "description"]

