version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  configuration: docs/config.py
  fail_on_warning: false
  
formats:
  - pdf
  
python:
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
